fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api'

api_login_check:
    path: /api/login_check

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
